# Generated by Django 6.0 on 2026-02-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('employee_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_location', models.CharField(max_length=100)),
                ('empoyee_phone', models.CharField(max_length=100)),
                ('employee_email', models.CharField(max_length=100)),
            ],
        ),
    ]
