# Generated by Django 6.0 on 2026-02-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employerdeatils',
            fields=[
                ('empid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('empmail', models.CharField(max_length=100)),
                ('emploc', models.CharField(max_length=100)),
                ('empphone', models.CharField(max_length=100)),
            ],
        ),
    ]
