# Generated by Django 6.0 on 2026-02-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerdeatils',
            name='empname',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
    ]
