# Generated by Django 6.0 on 2026-03-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='useraccount',
            fields=[
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('employer', 'Employer'), ('jobseeker', 'Job seeker')], max_length=20)),
            ],
        ),
    ]
